segmentation:
  ros__parameters:
    use_sim_time: true
    cam_center: 30
    segmentation_model: "yolo11m-seg"
    cam_top_threshold: 0.001
    cam_bot_threshold: 0.001
lidar_limiter:
  ros__parameters:
    maxrange: 1