# Segmentation configuration
segmentation:
  ros__parameters:
    segmentation_model: "yolo11m-seg.pt"
    cam_center: 30
    cam_count: 6
    view_p: 0.30
    view_h: 0.25
    fov_h: 56.2
# LiDAR configuration
lidar_limiter:
  ros__parameters:
    maxrange: 5