hazard_lookup = {
    # Kendaraan - Hazard Tinggi (7–10)
    "car": 9,
    "bus": 9,
    "truck": 9,
    "motorcycle": 8,
    "bicycle": 7,
    "train": 10,
    "airplane": 10,
    "boat": 8,

    # Makhluk hidup - Hazard Sedang (4–6)
    "person": 6,
    "dog": 5,
    "cat": 4,
    "horse": 6,
    "sheep": 5,
    "cow": 5,
    "bird": 4,
    "elephant": 6,
    "bear": 6,
    "zebra": 5,
    "giraffe": 5,

    # Lain-lain - Hazard Rendah (1–3)
    "traffic light": 2,
    "stop sign": 2,
    "parking meter": 2,
    "bench": 2,
    "backpack": 1,
    "umbrella": 2,
    "handbag": 1,
    "tie": 1,
    "suitcase": 2,
    "frisbee": 1,
    "skateboard": 1,
    "sports ball": 2,
    "kite": 1,
    "bottle": 1,
    "cup": 1,
    "fork": 1,
    "knife": 2,
    "spoon": 1,
    "bowl": 1,
    "banana": 1,
    "apple": 1,
    "sandwich": 1,
    "orange": 1,
    "broccoli": 1,
    "carrot": 1,
    "hot dog": 1,
    "pizza": 1,
    "donut": 1,
    "cake": 1,
    "chair": 2,
    "couch": 2,
    "potted plant": 2,
    "bed": 2,
    "dining table": 2,
    "tv": 1,
    "laptop": 1,
    "mouse": 1,
    "remote": 1,
    "keyboard": 1,
    "cell phone": 1,
    "microwave": 1,
    "oven": 1,
    "toaster": 1,
    "sink": 2,
    "refrigerator": 2,
    "book": 1,
    "clock": 1,
    "vase": 1,
    "scissors": 1,
    "teddy bear": 1,
    "hair drier": 1,
    "toothbrush": 1
}
